name: ssl
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py37h06a4308_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - freetype=2.10.4=h5ab3b9f_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.2.0=h3942068_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.3.0=py37h54f3939_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py37hff7bd54_0
  - olefile=0.46=py37_0
  - openssl=1.1.1l=h7f8727e_0
  - pillow=8.1.2=py37he98fc37_0
  - pip=20.3.3=py37h06a4308_0
  - python=3.7.10=hdb3f193_0
  - pytorch=1.7.1=py3.7_cuda10.2.89_cudnn7.6.5_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.15.0=py37h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.11.0
    - argcomplete==1.12.3
    - boto==2.49.0
    - cached-property==1.5.2
    - cachetools==4.2.1
    - cffi==1.14.6
    - chardet==4.0.0
    - click==8.0.1
    - crcmod==1.7
    - cryptography==3.4.7
    - cycler==0.10.0
    - fasteners==0.16.3
    - filelock==3.0.12
    - gcs-oauth2-boto-plugin==2.7
    - gensim==4.0.1
    - google-apitools==0.5.32
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - google-reauth==0.1.1
    - grpcio==1.35.0
    - gsutil==4.65
    - gym==0.18.3
    - h5py==3.2.1
    - higher==0.2.1
    - httplib2==0.19.1
    - huggingface-hub==0.0.12
    - idna==2.10
    - importlib-metadata==3.4.0
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - learn2learn==0.1.5
    - markdown==3.3.3
    - matplotlib==3.4.1
    - metann==0.2.9
    - mock==2.0.0
    - monotonic==1.6
    - numpy==1.19.5
    - oauth2client==4.1.3
    - oauthlib==3.1.0
    - packaging==21.0
    - pandas==1.3.0
    - pbr==5.6.0
    - progress==1.5
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyglet==1.5.15
    - pyopenssl==20.0.1
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pyu2f==0.1.5
    - pyyaml==5.4.1
    - regex==2021.8.3
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - retry-decorator==1.1.1
    - rsa==4.7
    - sacremoses==0.0.45
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - sklearn==0.0
    - smart-open==5.1.0
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.2
    - threadpoolctl==2.1.0
    - tokenizers==0.10.3
    - torchaudio==0.7.2
    - torchvision==0.8.2
    - tqdm==4.61.1
    - transformers==4.9.2
    - urllib3==1.26.3
    - werkzeug==1.0.1
    - zipp==3.4.0
prefix: /gs/hs0/tga-tslab/wyidong/anaconda3/envs/ssl
