save_dir: ./saved_models
save_name: freematch_svhn_40_0
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1
num_train_iter: 1048576
num_eval_iter: 5000
num_labels: 40
batch_size: 64
eval_batch_size: 1024
hard_label: True
T: 0.5
ulb_loss_ratio: 1.0
ent_loss_ratio: 0.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
net: WideResNet
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data
dataset: svhn
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
alg: freematch
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10045
dist_backend: nccl
gpu: None
