save_dir: ./saved_models
save_name: fixmatch_imagenet_100000_0
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1
num_train_iter: 2000000
num_eval_iter: 10000
num_labels: 100000
batch_size: 32
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0003
amp: False
net: ResNet50
net_from_name: False
depth: 0
widen_factor: 0
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data
dataset: imagenet
train_sampler: RandomSampler
num_classes: 1000
num_workers: 1
alg: fixmatch
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10010
dist_backend: nccl
gpu: None
